// This catalog ships inside the extension. Detection never downloads rules or text.
// `validated` means a syntax/checksum check, not proof that a value belongs to a person.
const rule = (id, title, kind, category, policyGroup, method, description) =>
  Object.freeze({ id, title, kind, category, policyGroup, method, description });

export const RULES = Object.freeze([
  rule(
    'email.standard',
    'Email addresses',
    'EMAIL',
    'contact',
    'redactEmails',
    'pattern',
    'Ordinary email addresses, including Unicode domains and local parts.',
  ),
  rule(
    'email.obfuscated',
    'Obfuscated email addresses',
    'EMAIL',
    'contact',
    'redactEmails',
    'heuristic',
    'Email addresses written with [at], (at), [dot] or (dot).',
  ),
  rule(
    'email.labeled',
    'Labeled email addresses',
    'EMAIL',
    'contact',
    'redactEmails',
    'context',
    'Addresses following an email label, including internal domains.',
  ),
  rule(
    'phone.international',
    'International phone numbers',
    'PHONE',
    'contact',
    'redactPhones',
    'validated',
    'Valid number formats and explicit +country numbers with a possible national length, using bundled libphonenumber full metadata. Possible-length matches can include reserved/unallocated ranges.',
  ),
  rule(
    'phone.labeled',
    'Labeled phone numbers',
    'PHONE',
    'contact',
    'redactPhones',
    'context',
    'Phone/mobile/telephone/fax labels protect plausible local numbers, extensions and short forms.',
  ),
  rule(
    'card.payment',
    'Payment card numbers',
    'CARD',
    'financial',
    'redactCards',
    'validated',
    '13–19 digit payment card numbers that pass the Luhn checksum.',
  ),
  rule(
    'card.contextual',
    'Labeled payment card data',
    'CARD',
    'financial',
    'redactCards',
    'context',
    'Card/PAN labels protect 12–19 digit values even when a checksum is mistyped; labeled CVV/CVC/PIN are protected too.',
  ),
  rule(
    'bank.iban',
    'International bank accounts (IBAN)',
    'IBAN',
    'financial',
    'redactBankAccounts',
    'validated',
    'Supported country length, alphanumeric structure and ISO 13616 MOD-97 checksum. Does not validate country-specific BBAN substructure or bank/account assignment.',
  ),
  rule(
    'bank.account',
    'Labeled bank account details',
    'BANK',
    'financial',
    'redactBankAccounts',
    'context',
    'Bank/account/routing/sort-code labels; syntax alone cannot identify account ownership.',
  ),
  rule(
    'id.us_ssn',
    'US Social Security numbers',
    'ID',
    'identifiers',
    'redactIdentifiers',
    'validated',
    'Formatted SSNs with valid area/group/serial ranges; labeled compact SSNs.',
  ),
  rule(
    'id.uk_nino',
    'UK National Insurance numbers',
    'ID',
    'identifiers',
    'redactIdentifiers',
    'pattern',
    'The National Insurance prefix, six digits and A–D suffix pattern.',
  ),
  rule(
    'id.ru_passport',
    'Russian passport numbers',
    'ID',
    'identifiers',
    'redactIdentifiers',
    'context',
    'Passport labels followed by a 4 digit series and 6 digit number.',
  ),
  rule(
    'id.ru_inn',
    'Russian tax IDs (INN)',
    'ID',
    'identifiers',
    'redactIdentifiers',
    'context',
    'Labeled 10 or 12 digit INN values, including mistyped checksums.',
  ),
  rule(
    'id.ru_snils',
    'Russian pension IDs (SNILS)',
    'ID',
    'identifiers',
    'redactIdentifiers',
    'validated',
    'Formatted SNILS with checksum validation; SNILS labels protect mistyped values too.',
  ),
  rule(
    'id.eu_tax',
    'European tax and identity IDs',
    'ID',
    'identifiers',
    'redactIdentifiers',
    'validated',
    'Spanish DNI/NIE and Italian codice fiscale checksums; label-based protection for PESEL and other European tax IDs.',
  ),
  rule(
    'id.canada_sin',
    'Canadian Social Insurance numbers',
    'ID',
    'identifiers',
    'redactIdentifiers',
    'context',
    'SIN labels followed by nine digits.',
  ),
  rule(
    'id.india_aadhaar',
    'Indian Aadhaar identifiers',
    'ID',
    'identifiers',
    'redactIdentifiers',
    'validated',
    'Grouped Aadhaar numbers with a Verhoeff checksum; labeled Aadhaar values.',
  ),
  rule(
    'id.national',
    'Other labeled national identifiers',
    'ID',
    'identifiers',
    'redactIdentifiers',
    'context',
    'Country-specific labels for CPF/CNPJ, NRIC, TFN, NIR, NHS, resident ID and similar identifiers.',
  ),
  rule(
    'id.generic',
    'Labeled personal identifiers',
    'ID',
    'identifiers',
    'redactIdentifiers',
    'context',
    'Passport, license, employee/customer, patient, student, insurance and national-ID labels.',
  ),
  rule(
    'id.birth_date',
    'Labeled dates of birth',
    'ID',
    'personal',
    'redactIdentifiers',
    'context',
    'DOB, date-of-birth, birth-date and birthday fields. Ordinary dates remain untouched.',
  ),
  rule(
    'secret.openai',
    'OpenAI API keys',
    'SECRET',
    'credentials',
    'redactSecrets',
    'pattern',
    'sk-, sk-proj- and sk-svcacct- key shapes; prefix matching cannot confirm validity.',
  ),
  rule(
    'secret.anthropic',
    'Anthropic API keys',
    'SECRET',
    'credentials',
    'redactSecrets',
    'pattern',
    'sk-ant- key shapes.',
  ),
  rule(
    'secret.aws',
    'AWS access identifiers',
    'SECRET',
    'credentials',
    'redactSecrets',
    'pattern',
    'AKIA/ASIA access-key IDs and other AWS access identifier prefixes.',
  ),
  rule(
    'secret.github',
    'GitHub access tokens',
    'SECRET',
    'credentials',
    'redactSecrets',
    'pattern',
    'ghp_/gho_/ghu_/ghs_/ghr_ and github_pat_ token shapes.',
  ),
  rule(
    'secret.gitlab',
    'GitLab tokens',
    'SECRET',
    'credentials',
    'redactSecrets',
    'pattern',
    'glpat-, gldt-, glrt- and related GitLab token prefixes.',
  ),
  rule(
    'secret.google',
    'Google API keys',
    'SECRET',
    'credentials',
    'redactSecrets',
    'pattern',
    'AIza key shapes and Google OAuth access tokens.',
  ),
  rule(
    'secret.stripe',
    'Stripe restricted and secret keys',
    'SECRET',
    'credentials',
    'redactSecrets',
    'pattern',
    'sk_live_, sk_test_, rk_live_, rk_test_ and webhook signing-secret shapes.',
  ),
  rule(
    'secret.slack',
    'Slack tokens',
    'SECRET',
    'credentials',
    'redactSecrets',
    'pattern',
    'xoxb/xoxp/xoxa/xoxr/xoxs Slack token shapes.',
  ),
  rule(
    'secret.npm',
    'npm access tokens',
    'SECRET',
    'credentials',
    'redactSecrets',
    'pattern',
    'npm_ access-token shapes.',
  ),
  rule(
    'secret.shopify',
    'Shopify access tokens',
    'SECRET',
    'credentials',
    'redactSecrets',
    'pattern',
    'shpat_/shpca_/shppa_/shpss_ token shapes.',
  ),
  rule(
    'secret.twilio',
    'Twilio API keys',
    'SECRET',
    'credentials',
    'redactSecrets',
    'pattern',
    'SK followed by a 32 character hexadecimal API-key ID.',
  ),
  rule(
    'secret.sendgrid',
    'SendGrid API keys',
    'SECRET',
    'credentials',
    'redactSecrets',
    'pattern',
    'SG. two-part API-key shapes.',
  ),
  rule(
    'secret.huggingface',
    'Hugging Face access tokens',
    'SECRET',
    'credentials',
    'redactSecrets',
    'pattern',
    'hf_ access-token shapes.',
  ),
  rule(
    'secret.service',
    'Other service credentials',
    'SECRET',
    'credentials',
    'redactSecrets',
    'pattern',
    'DigitalOcean, Linear, Postman, Telegram, Discord and Microsoft connection-string credentials.',
  ),
  rule(
    'secret.jwt',
    'JSON Web Tokens',
    'SECRET',
    'credentials',
    'redactSecrets',
    'validated',
    'Three-part base64url JWTs with a JSON header and payload; signatures are not verified.',
  ),
  rule(
    'secret.private_key',
    'Private key material',
    'SECRET',
    'credentials',
    'redactSecrets',
    'pattern',
    'PEM/OpenSSH/PGP private key blocks, including incomplete blocks.',
  ),
  rule(
    'secret.assignment',
    'Labeled passwords and tokens',
    'SECRET',
    'credentials',
    'redactSecrets',
    'context',
    'Password, API-key, client-secret, access-token and similar assignments.',
  ),
  rule(
    'secret.bearer',
    'Authorization credentials',
    'SECRET',
    'credentials',
    'redactSecrets',
    'context',
    'Bearer/Basic authorization credentials and labeled cookies.',
  ),
  rule(
    'secret.url_credentials',
    'Credentials in URLs',
    'SECRET',
    'credentials',
    'redactSecrets',
    'context',
    'User:password URL credentials and secret-bearing URL query parameters.',
  ),
  rule(
    'person.name',
    'Labeled personal names',
    'PERSON',
    'personal',
    'redactNames',
    'context',
    'Name/full-name/employee-name/patient-name/customer-name labels and localized equivalents. A separate bounded lexicon heuristic covers selected unlabeled names.',
  ),
  rule(
    'address.labeled',
    'Labeled postal addresses',
    'ADDRESS',
    'location',
    'redactAddresses',
    'context',
    'Address/home-address/billing/shipping/postal-address labels, including Unicode text.',
  ),
  rule(
    'id.cis',
    'Labeled Russia and neighboring-country identifiers',
    'ID',
    'identifiers',
    'redactIdentifiers',
    'context',
    'Regional passport, tax, insurance and personal-ID labels including IIN/ЖСН, RNOKPP/РНОКПП, IDNP, FIN/FİN, PIN/ПИН and JSHSHIR/ПИНФЛ. Context matching protects mistyped values; no additional country checksum is claimed.',
  ),
  rule(
    'person.lexicon',
    'Common given names with capitalized surnames',
    'PERSON',
    'personal',
    'redactNames',
    'heuristic',
    'Packaged multilingual given-name lexicon followed by a capitalized surname, with optional Cyrillic patronymic. Bounded heuristic, not comprehensive name recognition; can match fictional/product names.',
  ),
  rule(
    'address.street_de',
    'German street and house numbers',
    'ADDRESS',
    'location',
    'redactAddresses',
    'heuristic',
    'Street name ending in Straße/Strasse/str./Weg/Allee/Platz/Gasse/Ufer/Ring plus a house number, including lowercase text and number ranges. Does not cover every street name or entire postal address.',
  ),
  rule(
    'address.street_cis',
    'Regional street and house numbers',
    'ADDRESS',
    'location',
    'redactAddresses',
    'heuristic',
    'Cyrillic street prefixes with house/apartment numbers and selected Kazakh, Kyrgyz, Uzbek, Azerbaijani, Turkmen, Armenian, Georgian and Romanian street markers. Bounded heuristic; full multiline addresses still need labels or custom terms.',
  ),
  rule(
    'network.ip_address',
    'IP and hardware addresses',
    'IP',
    'network',
    'redactNetwork',
    'validated',
    'IPv4, IPv6 and MAC addresses. Optional because many technical prompts legitimately contain public addresses.',
  ),
]);

export const RULES_BY_ID = Object.freeze(Object.fromEntries(RULES.map((r) => [r.id, r])));
export const DEFAULT_ENABLED_RULE_IDS = Object.freeze(
  RULES.filter((r) => r.policyGroup !== 'redactNetwork').map((r) => r.id),
);
// Alternative name useful to tools which display a detection-rule catalog.
export const DETECTION_RULES = RULES;
